#!/bin/bash
clear

score/sheet.py src/data-1.inc 1
fasm src/main-1.asm main-1.com
score/sheet.py src/data-2.inc 2
fasm src/main-2.asm main-2.com
score/sheet.py analysis.txt

#watch -n1 "git status --short ; echo -- ; score/sheet.py src/score.inc fin ; fasm src/prelude1.asm prelude1.com"
